service: aws-node-express-api
frameworkVersion: "3"

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'us-east-1'}
  prismaEngine:
    offline: "node_modules/.prisma/client/*.node"
    staging: "node_modules/.prisma/client/libquery_engine-rhel*"
    prod: "node_modules/.prisma/client/libquery_engine-rhel*"
  esbuild:
    platform: "node"
    target: node18
    sourcemap: linked
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
    reloadHandler: true

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  httpApi:
    cors: true

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"

package:
  patterns:
    - "!**/*.ts"
    - ${self:custom.prismaEngine.${self:custom.stage}}
    - "node_modules/.prisma/client/schema.prisma"
  individually: true

plugins:
  - serverless-esbuild
  - serverless-offline
